### PR TITLE
Added snaps and titles

### PR DESCRIPTION
**Pull request by masanasake**

### CODE REVIEW

**Comment by RobLoach** [comment]
The boxart looks pretty washed out :thinking: 
Screenshot at 2022-06-03 15-44-13

**Comment by masanasake** [comment]
@MarcoEstevez any thoughts on this? I can just revert the box art if no one else thinks the current one is notably dark (and pink)

**Comment by MarcoEstevez** [comment]
Looks a bit over exposed while the current one its kind of dark, what about something in between?

**Comment by masanasake** [comment]
Added a new one. Any better @RobLoach ?

**Review by RobLoach — APPROVED** [review]

**Comment by masanasake** [comment]
Sorry, maybe give it another look. I noticed some stray marks and a circle on the horse's face. Should be fixed. Sorry

**Pull request merged**
