### PR TITLE
Big pull

### PR DESCRIPTION
**Pull request by Setilla**

### CODE REVIEW

**Comment by MarcoEstevez** [comment]
@Setilla there is a conflict, mind you resolve it, other than this, looks great so far

**Comment by RobLoach** [comment]
Looks like a bunch of these are 500px wide. While 500 is fine, we do target **512px** wide. No big deal, but it can affect scaling the images :wink:

**Comment by Setilla** [comment]
> Looks like a bunch of these are 500px wide. While 500 is fine, we do target **512px** wide. No big deal, but it can affect scaling the images wink

I'll see if I can find better scans of those and the new uploads.

**Review by RobLoach — APPROVED** [review]

**Comment by RobLoach** [comment]
thanks so much!

**Pull request merged**
